version: "3.7"
 
services: 
  flask:
    build: ./flaska
    container_name: mshapiflask
    image: mshapiflask:0.1.0
    restart: always
    environment:
      - APP_NAME=FlaskApp
    #expose:
    #    - 8100
    ports:    
       - "8100:8100"
  nginx:
    build: ./nginxd
    container_name: mshapinginx
    image: mshapinginx:1.0.0
    restart: always
    ports:
      - "8150:8150"
    depends_on:
      - flask
      
  #db:
    #image: postgres
    #container_name: postgres
    #volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
    #environment:
    #  POSTGRES_DB: db_name
    #  POSTGRES_USER: postgres_n
    #  POSTGRES_PASSWORD: postgres_p
    #ports:
    #  - 5432:5432